// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBrrYrtyVIkvuffTp77_DAus-8mp4KgI',
    appId: '1:93772200985:web:dabce7702cae5860cffe88',
    messagingSenderId: '93772200985',
    projectId: 'overbook-my-show',
    authDomain: 'overbook-my-show.firebaseapp.com',
    storageBucket: 'overbook-my-show.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8FbOCSvNmXo9mzkb1pmbgWVJ-HR4tQoY',
    appId: '1:93772200985:android:f9a92b934b413c69cffe88',
    messagingSenderId: '93772200985',
    projectId: 'overbook-my-show',
    storageBucket: 'overbook-my-show.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWaMTF0Ubaz7C1zwhsaYz2mmfpz1d8xs',
    appId: '1:93772200985:ios:6fbe02b988d90647cffe88',
    messagingSenderId: '93772200985',
    projectId: 'overbook-my-show',
    storageBucket: 'overbook-my-show.appspot.com',
    iosBundleId: 'com.example.overbookMyShow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZWaMTF0Ubaz7C1zwhsaYz2mmfpz1d8xs',
    appId: '1:93772200985:ios:ed46d5310b1955f1cffe88',
    messagingSenderId: '93772200985',
    projectId: 'overbook-my-show',
    storageBucket: 'overbook-my-show.appspot.com',
    iosBundleId: 'com.example.overbookMyShow.RunnerTests',
  );
}
